### ISSUE TITLE
Infinite loop in uploader-gui.py

### ISSUE THREAD

**Issue by randomouscrap98** [MrBlinky/Arduboy-Python-Utilities#8]
When applying a contrast patch, the program gets into an infinite loop (line 342: https://github.com/MrBlinky/Arduboy-Python-Utilities/blob/e9f8e860bdd806f6937eb30060f5e18d3584c4cd/uploader-gui.py#L342-L350), as the lcdBootProgram_addr will always be the location of the first 7 known bytes, but those 7 are not changed if the ssd1309 patch is not applied.

**Comment by MrBlinky** [comment]
You're right. when the SSD1309 patch isn't also checked, it infinite loops. Will fix. Thanks for  reporting the issue.

**Comment by MrBlinky** [comment]
fixed now
